apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-resume-pvc
  namespace: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path