apiVersion: v1
kind: Service
metadata:
  name: node-service-template
  namespace: default
spec:
  selector:
    app: node-service-template
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
